### PR TITLE
Remove unneeded casting.

### PR DESCRIPTION
**Pull request by xXAndrew28Xx**

### CODE REVIEW

**Comment by nfell2009** [comment]
+1

**Comment by Nicofisi** [comment]
+2,5/10

**Comment by F8te** [comment]
+3/12

**Comment by Nicofisi** [comment]
-1,5

**Comment by TheLimeGlass** [comment]
This was already fixed in 1.5.6 when I noticed it, but thanks for the help. Any feedback/help is taken. Updating the github next update.

**Pull request closed without merging**
