### PR TITLE
Improved readability, reliability and fixed all bugs.

### PR DESCRIPTION
**Pull request by Nicofisi**
So hey, after deliberations with many members of skUnity I decided to modify the code of Skellett to include all of their suggestions. Please merge.

### CODE REVIEW

**Comment by TonyMaster21** [comment]
This looks really good. I hope it fixes my issues that i've been having with Skellet and SkellettProxy!

**Comment by Nicofisi** [comment]
Thanks for the positive opinion @TonyMaster21. It will for sure motivate me to continue contributing to this plugin in the future!

**Comment by minemidnight** [comment]
merge now

**Comment by WheezyGold7931** [comment]
This is ready to merge

**Comment by Nicofisi** [comment]
:(

**Comment by minemidnight** [comment]
LimeGlass I Would Really Consider Re Opening This Pull Request. It Has Some Very Good Lessons On How To Improve Your Java Code.

**Pull request closed without merging**
